config/routes.rb
Rails.application.routes.draw do
  resources :job_applications
  resources :job_listings
  resources :student_profiles
  resources :skills do
    member do
      get :add_user_to, :remove_user_from

    end
  end
  resources :skill_categories
  resources :company_profiles do
      collection do
          post 'search'
      end
  end

  devise_for :users, controllers: { registrations: "registrations" }
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/skill_category.rb
class SkillCategory < ApplicationRecord
  has_many :skills
end

app/controllers/skill_categories_controller.rb
class SkillCategoriesController < ApplicationController
  before_action :set_skill_category, only: [:show, :edit, :update, :destroy]

  # GET /skill_categories
  # GET /skill_categories.json
  def index
    @skill_categories = SkillCategory.all
  end

  # GET /skill_categories/1
  # GET /skill_categories/1.json
  def show
  end

  # GET /skill_categories/new
  def new
    @skill_category = SkillCategory.new
  end

  # GET /skill_categories/1/edit
  def edit
  end

  # POST /skill_categories
  # POST /skill_categories.json
  def create
    @skill_category = SkillCategory.new(skill_category_params)

    respond_to do |format|
      if @skill_category.save
        format.html { redirect_to @skill_category, notice: 'Skill category was successfully created.' }
        format.json { render :show, status: :created, location: @skill_category }
      else
        format.html { render :new }
        format.json { render json: @skill_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skill_categories/1
  # PATCH/PUT /skill_categories/1.json
  def update
    respond_to do |format|
      if @skill_category.update(skill_category_params)
        format.html { redirect_to @skill_category, notice: 'Skill category was successfully updated.' }
        format.json { render :show, status: :ok, location: @skill_category }
      else
        format.html { render :edit }
        format.json { render json: @skill_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skill_categories/1
  # DELETE /skill_categories/1.json
  def destroy
    @skill_category.destroy
    respond_to do |format|
      format.html { redirect_to skill_categories_url, notice: 'Skill category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill_category
      @skill_category = SkillCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def skill_category_params
      params.require(:skill_category).permit(:name, :description)
    end
end

app/helpers/skill_categories_helper.rb
module SkillCategoriesHelper
end

app/views/skill_categories/_form.html.erb
<%= simple_form_for(@skill_category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/skill_categories/edit.html.erb
<h1>Editing Skill Category</h1>

<%= render 'form', skill_category: @skill_category %>

<%= link_to 'Show', @skill_category %> |
<%= link_to 'Back', skill_categories_path %>

app/views/skill_categories/index.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
  <thead>
    <tr>
      <th>Skill category</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan='3'><th>
      </tr>

  <tbody>


  <tbody>
    <% @skill_categories.each do |skill_category| %>
      <tr>
        <td><%= skill_category.name %></td>
        <td><%= skill_category.description %></td>
        <td><%= link_to 'Show', skill_category %></td>
        <td><%= link_to 'Edit', edit_skill_category_path(skill_category) %></td>
        <td><%= link_to 'Destroy', skill_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Skill Category', new_skill_category_path %>

app/views/skill_categories/new.html.erb
<h1>New Skill Category</h1>

<%= render 'form', skill_category: @skill_category %>

<%= link_to 'Back', skill_categories_path %>

app/views/skill_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @skill_category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @skill_category.description %>
</p>

<%= link_to 'Edit', edit_skill_category_path(@skill_category) %> |
<%= link_to 'Back', skill_categories_path %>