config/routes.rb
Rails.application.routes.draw do
  resources :job_applications
  resources :job_listings
  resources :student_profiles
  resources :skills do
    member do
      get :add_user_to, :remove_user_from

    end
  end
  resources :skill_categories
  resources :company_profiles do
      collection do
          post 'search'
      end
  end

  devise_for :users, controllers: { registrations: "registrations" }
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company_profile.rb
class CompanyProfile < ApplicationRecord
  belongs_to :user
  has_many :job_listings
  validates :first_name, :last_name, :phone, :company_name, :company_type, :street, :suburb, :postcode, :country, presence: true
  mount_uploader :logo, CompanyProfileLogoUploader
  geocoded_by :formatted_address   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates


  def contact_name
    first_name + ' ' + last_name
  end

  def formatted_address
    [street, suburb, postcode, country].join(', ')
  end

end

app/models/job_application.rb
class JobApplication < ApplicationRecord
  belongs_to :job_listing
  belongs_to :user
end

app/models/job_listing.rb
class JobListing < ApplicationRecord
  belongs_to :user
  belongs_to :company_profile
  has_many :job_listing_skills
  has_many :skills, through: :job_listing_skills
  has_many :job_applications
  has_many :users, through: :job_applications
end

app/models/job_listing_skill.rb
class JobListingSkill < ApplicationRecord
  belongs_to :job_listing
  belongs_to :skill
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :skill_category
  has_many :user_skills
  has_many :users, through: :user_skills
  has_many :job_listing_skills
  has_many :job_listings, through: :job_listing_skills
end

app/models/skill_category.rb
class SkillCategory < ApplicationRecord
  has_many :skills
end

app/models/student_profile.rb
class StudentProfile < ApplicationRecord
  belongs_to :user

  mount_uploader :cv, StudentProfileCvUploader
  mount_uploader :photo, CompanyProfileLogoUploader

  def student_name
    first_name + ' ' + last_name
  end

  def student_location
    [city, country].join(', ')
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :company_profiles
  has_one :student_profile
  has_many :job_listings
  has_many :user_skills
  has_many :skills, through: :user_skills
  has_many :job_applications
  has_many :job_listings, through: :job_applications

  rolify

  after_create :assign_role

  def assign_role
    unless user_type.nil?
      if user_type == 'company'
        add_role :company_rep
      elsif user_type == 'student'
        add_role :student
      end
    end
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_skill.rb
class UserSkill < ApplicationRecord
  belongs_to :user
  belongs_to :skill
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @job_listings = JobListing.order(:created_at)
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:remove_user_from, :add_user_to, :show, :edit, :update, :destroy]

  def add_user_to
    @skill.users << current_user
    redirect_to :back
  end

  def remove_user_from
    @skill.users.delete(current_user)
    redirect_to :back
  end

  # GET /skills
  # GET /skills.json
  def index
    @skills = Skill.all
  end

  # GET /skills/1
  # GET /skills/1.json
  def show
  end

  # GET /skills/new
  def new
    @skill = Skill.new
  end

  # GET /skills/1/edit
  def edit
  end

  # POST /skills
  # POST /skills.json
  def create
    @skill = Skill.new(skill_params)

    respond_to do |format|
      if @skill.save
        format.html { redirect_to @skill, notice: 'Skill was successfully created.' }
        format.json { render :show, status: :created, location: @skill }
      else
        format.html { render :new }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skills/1
  # PATCH/PUT /skills/1.json
  def update
    respond_to do |format|
      if @skill.update(skill_params)
        format.html { redirect_to @skill, notice: 'Skill was successfully updated.' }
        format.json { render :show, status: :ok, location: @skill }
      else
        format.html { render :edit }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    @skill.destroy
    respond_to do |format|
      format.html { redirect_to skills_url, notice: 'Skill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_skill
      @skill = Skill.find(params[:id])
    end

    # Use callbacks to share common setup or constraints between actions.
    # Never trust parameters from the scary internet, only allow the white list through.
    def skill_params
      params.require(:skill).permit(:skill_category_id, :name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/company_profiles_helper.rb
module CompanyProfilesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/job_applications_helper.rb
module JobApplicationsHelper
end

app/helpers/job_listings_helper.rb
module JobListingsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jobapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class='container'>
      <%= render 'shared/alerts' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_alerts.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><p class="notice"><%= notice %></p></div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><p class="alert"><%= alert %></p></div>
<% end %>
<script>$(".alert" ).fadeOut(3000);</script>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Girly Jobs</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <!-- <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu">

              <% if current_user.has_role? :admin %>
              <li><a href="/skills">Skills</a></li>
              <li><a href="/skill_categories">Skills Category</a></li>
              <% end %>

              <% if current_user.has_role? :student and current_user.student_profile %>
              <li><%= link_to "My Profile", student_profile_path(current_user.student_profile) %>
              <% end %></li>

              <% if current_user.has_role? :company_rep %>
                  <% if current_user.company_profiles.any? %>
                  <% current_user.company_profiles.each do |company| %>
                  <li><%= link_to company.company_name, company_profile_path(company) %></li>
                <% end %>

              <% end %>
                <li><%= link_to 'Create company profile', new_company_profile_path %></li>
              <% end %>

              <li><%= link_to 'Add job listing', new_job_listing_path %></li>

              <li><a href="#">Something else here</a></li>



              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
          <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>