config/routes.rb
Rails.application.routes.draw do
  resources :job_applications
  resources :job_listings
  resources :student_profiles
  resources :skills do
    member do
      get :add_user_to, :remove_user_from

    end
  end
  resources :skill_categories
  resources :company_profiles do
      collection do
          post 'search'
      end
  end

  devise_for :users, controllers: { registrations: "registrations" }
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company_profile.rb
class CompanyProfile < ApplicationRecord
  belongs_to :user
  has_many :job_listings
  validates :first_name, :last_name, :phone, :company_name, :company_type, :street, :suburb, :postcode, :country, presence: true
  mount_uploader :logo, CompanyProfileLogoUploader
  geocoded_by :formatted_address   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates


  def contact_name
    first_name + ' ' + last_name
  end

  def formatted_address
    [street, suburb, postcode, country].join(', ')
  end

end

app/controllers/company_profiles_controller.rb
class CompanyProfilesController < ApplicationController
  before_action :set_company_profile, only: [:show, :edit, :update, :destroy]

  def search
    @company_profiles = CompanyProfile.near(params[:location] + ", Australia")
  end


  # GET /company_profiles
  # GET /company_profiles.json
  def index
    @company_profiles = CompanyProfile.all
  end

  # GET /company_profiles/1
  # GET /company_profiles/1.json
  def show
  end

  # GET /company_profiles/new
  def new
    @company_profile = CompanyProfile.new
  end

  # GET /company_profiles/1/edit
  def edit
  end

  # POST /company_profiles
  # POST /company_profiles.json
  def create
    @company_profile = CompanyProfile.new(company_profile_params)
    @company_profile.user = current_user
    respond_to do |format|
      if @company_profile.save
        format.html { redirect_to @company_profile, notice: 'Company profile was successfully created.' }
        format.json { render :show, status: :created, location: @company_profile }
      else
        format.html { render :new }
        format.json { render json: @company_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /company_profiles/1
  # PATCH/PUT /company_profiles/1.json
  def update
    respond_to do |format|
      if @company_profile.update(company_profile_params)
        format.html { redirect_to @company_profile, notice: 'Company profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @company_profile }
      else
        format.html { render :edit }
        format.json { render json: @company_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /company_profiles/1
  # DELETE /company_profiles/1.json
  def destroy
    @company_profile.destroy
    respond_to do |format|
      format.html { redirect_to company_profiles_url, notice: 'Company profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company_profile
      @company_profile = CompanyProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_profile_params
      params.require(:company_profile).permit(:first_name, :last_name, :phone, :company_name, :logo, :description, :street, :suburb, :postcode, :country, :latitude, :longitude, :company_culture, :company_type, :user_id)
    end
end

app/helpers/company_profiles_helper.rb
module CompanyProfilesHelper
end

app/views/company_profiles/_form.html.erb
<div class='row'>
    <div class='col-md-10 col-md-offset-1'>
        <div class='panel panel-default'>
          <div class='panel-heading'>
            <h2 class='panel-title'>New Company Profile</h2>
          </div>

          <div class='panel-body'>


<%= simple_form_for(@company_profile) do |f| %>

  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name, label: 'Enter your first name' %>
    <%= f.input :last_name, placeholder: 'Enter your last name' %>
    <%= f.input :phone %>
    <%= f.input :company_name %>
    <%= f.input :company_type, collection: ['Startup', 'Established Startup', 'Agency', 'Small Business', 'Other'] %>
    <%= f.input :logo %>
    <%= f.input :description, input_html: {rows: 5 } %>
    <%= f.input :street %>
    <%= f.input :suburb %>
    <%= f.input :postcode %>
    <%= f.input :country, priority: ['Australia', 'New Zealand'] %>
    <%= f.input :company_culture %>


  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/company_profiles/edit.html.erb
<h1>Editing Company Profile</h1>

<%= render 'form', company_profile: @company_profile %>

<%= link_to 'Show', @company_profile %> |
<%= link_to 'Back', company_profiles_path %>

app/views/company_profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Company Profiles</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Phone</th>
      <th>Company name</th>
      <th>Logo</th>
      <th>Description</th>
      <th>Street</th>
      <th>Suburb</th>
      <th>Postcode</th>
      <th>Country</th>
      <th>Company culture</th>
      <th>Company type</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @company_profiles.each do |company_profile| %>
      <tr>
        <td><%= company_profile.first_name %></td>
        <td><%= company_profile.last_name %></td>
        <td><%= company_profile.phone %></td>
        <td><%= company_profile.company_name %></td>
        <td><%= company_profile.logo %></td>
        <td><%= company_profile.description %></td>
        <td><%= company_profile.street %></td>
        <td><%= company_profile.suburb %></td>
        <td><%= company_profile.postcode %></td>
        <td><%= company_profile.country %></td>
        <td><%= company_profile.latitude %></td>
        <td><%= company_profile.longitude %></td>
        <td><%= company_profile.company_culture %></td>
        <td><%= company_profile.company_type %></td>
        <td><%= company_profile.user %></td>
        <td><%= link_to 'Show', company_profile %></td>
        <td><%= link_to 'Edit', edit_company_profile_path(company_profile) %></td>
        <td><%= link_to 'Destroy', company_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company Profile', new_company_profile_path %>

app/views/company_profiles/new.html.erb
<h1>New Company Profile</h1>

<%= render 'form', company_profile: @company_profile %>

<%= link_to 'Back', company_profiles_path %>

app/views/company_profiles/search.html.erb
<h2>Search results</h2>

<ul>
  <% @company_profiles.each do |profile| %>
    <li> <%= profile.company_name %></li>
    <% end %>
</ul>

app/views/company_profiles/show.html.erb
<div class="row">
  <div class="col-md-6">
   <div class="panel panel-default">
     <div class="panel-heading">
       <h2 class="panel-title">Company Profile</h>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-md-6">
          <%= cl_image_tag @company_profile.logo, class: 'img-responsive', alt: @company_profile.company_name + 'logo' %>
        </div>
        <div class="col-md-6">
        <h3><%= @company_profile.company_name %></h3>
        <p class="lead"><%= @company_profile.company_type %></p>
      </div>
    </div>
    <p><strong>Contact name:</strong> <%= @company_profile.contact_name %></p>
    <p><strong>Address:</strong> <%= @company_profile.formatted_address %></p>
     <div id="map"></div>
    <hr>
    <p><strong>Company info</strong></p><p><% @company_profile.description %></p>
    <p><strong>Company culture</strong></p><p><%= @company_profile.company_culture %></p>
    <% if @company_profile.user == current_user %>
     <%= link_to 'Edit company profile',
     edit_company_profile_path(@company_profile), class: 'btn btn-warning btn-sm' %>

     <%=link_to 'Add job listing', new_job_listing_path(company_profile: @company_profile), class: 'btn btn-info btn-sm' %>

     <%end%>
      </div>
    </div>
  </div>
</div>

<script>

      function initMap() {
        var myLatLng = {lat: <%= @company_profile.latitude %>, lng: <%= @company_profile.longitude %>};

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 15,
          center: myLatLng
        });

        var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: '<%= @company_profile.company_name %>'
        });
      }
    </script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCneAz85u87yiQIsR7ncVgbn_D256VtVdE&callback=initMap">
    </script>