config/routes.rb
Rails.application.routes.draw do
  resources :job_applications
  resources :job_listings
  resources :student_profiles
  resources :skills do
    member do
      get :add_user_to, :remove_user_from

    end
  end
  resources :skill_categories
  resources :company_profiles do
      collection do
          post 'search'
      end
  end

  devise_for :users, controllers: { registrations: "registrations" }
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student_profile.rb
class StudentProfile < ApplicationRecord
  belongs_to :user

  mount_uploader :cv, StudentProfileCvUploader
  mount_uploader :photo, CompanyProfileLogoUploader

  def student_name
    first_name + ' ' + last_name
  end

  def student_location
    [city, country].join(', ')
  end

end

app/controllers/student_profiles_controller.rb
class StudentProfilesController < ApplicationController
  before_action :set_student_profile, only: [:show, :edit, :update, :destroy]

  # GET /student_profiles
  # GET /student_profiles.json
  def index
    @student_profiles = StudentProfile.all
  end

  # GET /student_profiles/1
  # GET /student_profiles/1.json
  def show
    @skill_categories = SkillCategory.order(name: :asc)
  end

  # GET /student_profiles/new
  def new
    @student_profile = StudentProfile.new
  end

  # GET /student_profiles/1/edit
  def edit
  end

  # POST /student_profiles
  # POST /student_profiles.json
  def create
    @student_profile = StudentProfile.new(student_profile_params)
    @student_profile.user = current_user
    respond_to do |format|
      if @student_profile.save
        format.html { redirect_to @student_profile, notice: 'Student profile was successfully created.' }
        format.json { render :show, status: :created, location: @student_profile }
      else
        format.html { render :new }
        format.json { render json: @student_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /student_profiles/1
  # PATCH/PUT /student_profiles/1.json
  def update
    respond_to do |format|
      if @student_profile.update(student_profile_params)
        format.html { redirect_to @student_profile, notice: 'Student profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @student_profile }
      else
        format.html { render :edit }
        format.json { render json: @student_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_profiles/1
  # DELETE /student_profiles/1.json
  def destroy
    @student_profile.destroy
    respond_to do |format|
      format.html { redirect_to student_profiles_url, notice: 'Student profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_profile
      @student_profile = StudentProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_profile_params
      params.require(:student_profile).permit(:first_name, :last_name, :phone, :bio, :website, :github_username, :linkedin_url, :photo, :cv, :city, :country, :user_id)
    end
end

app/helpers/student_profiles_helper.rb
module StudentProfilesHelper
end

app/views/student_profiles/_form.html.erb
<%= simple_form_for(@student_profile) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :phone %>
    <%= f.input :bio %>
    <%= f.input :website %>
    <%= f.input :github_username %>
    <%= f.input :linkedin_url %>
    <%= f.input :photo %>
    <%= f.input :cv %>
    <%= f.input :city %>
    <%= f.input :country %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/student_profiles/edit.html.erb
<h1>Editing Student Profile</h1>

<%= render 'form', student_profile: @student_profile %>

<%= link_to 'Show', @student_profile %> |
<%= link_to 'Back', student_profiles_path %>

app/views/student_profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Student Profiles</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Phone</th>
      <th>Bio</th>
      <th>Website</th>
      <th>Github username</th>
      <th>Linkedin url</th>
      <th>Photo</th>
      <th>Cv</th>
      <th>City</th>
      <th>Country</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @student_profiles.each do |student_profile| %>
      <tr>
        <td><%= student_profile.first_name %></td>
        <td><%= student_profile.last_name %></td>
        <td><%= student_profile.phone %></td>
        <td><%= student_profile.bio %></td>
        <td><%= student_profile.website %></td>
        <td><%= student_profile.github_username %></td>
        <td><%= student_profile.linkedin_url %></td>
        <td><%= student_profile.photo %></td>
        <td><%= student_profile.cv %></td>
        <td><%= student_profile.city %></td>
        <td><%= student_profile.country %></td>
        <td><%= student_profile.user %></td>
        <td><%= link_to 'Show', student_profile %></td>
        <td><%= link_to 'Edit', edit_student_profile_path(student_profile) %></td>
        <td><%= link_to 'Destroy', student_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student Profile', new_student_profile_path %>

app/views/student_profiles/new.html.erb
<h1>New Student Profile</h1>

<%= render 'form', student_profile: @student_profile %>

<%= link_to 'Back', student_profiles_path %>

app/views/student_profiles/show.html.erb
<div class="row">
  <div class="col-md-6">
   <div class="panel panel-default">
     <div class="panel-heading">
       <h2 class="panel-title">Student Profile</h>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-md-6">
          <%= cl_image_tag @student_profile.photo, class: 'img-responsive', alt: @student_profile.student_name + 'photo' %>
        </div>
        <div class="col-md-6">
        <h3><%= @student_profile.student_name %></h3>
        <p class="lead"><%= @student_profile.student_location %></p>
      </div>
    </div>
    <p><strong>Contact name:</strong> <%= @student_profile.linkedin_url %></p>
    <p><strong>Website:</strong> <%= @student_profile.website %></p>
    <p><strong>Gibhub User Name:</strong> <%= @student_profile.github_username %></p>
    <hr>
    <p><strong>Student Bio</strong></p><p><% @student_profile.bio %></p>
      <td><%= link_to '<i class="fa fa-download"></i> My CV'.html_safe, @student_profile.cv.url, class: 'btn btn-info btn-sm', target: '_blank' %></p>

    <p><strong>City</strong></p><p><%= @student_profile.city %></p>
    <% if @student_profile.user == current_user %>
     <%= link_to 'Edit student profile',
     edit_student_profile_path(@student_profile), class: 'btn btn-warning btn-sm' %>
     <%end%>

     <!-- Button trigger modal -->
     <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal">
       Add Skills
     </button>
     <hr>
     <h4>My Skills</h4>
     <ul>
       <% @student_profile.user.skills.each do |skill| %>
       <li><%= skill.name %></li>
       <% end %>
     </ul>
   </div>
 </div>
 </div>
 </div>


     <!-- Modal -->
     <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
       <div class="modal-dialog" role="document">
         <div class="modal-content">
           <div class="modal-header">
             <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
             <h4 class="modal-title" id="myModalLabel">Add skills to my profile</h4>
           </div>

           <div class="modal-body">

             <% @skill_categories.each do |category| %>
             <p><strong><%= category.name %></strong></p>
             <% category.skills.each do |skill| %>

             <% if skill.users.include?(current_user) %>
             <%= link_to skill.name, remove_user_from_skill_path(skill), class: 'btn btn-success btn-sm' %>
             <% else %>
              <%= link_to skill.name, add_user_to_skill_path(skill), class: 'btn btn-primary btn-sm' %>
              <%end%>
             <%end%>
             <hr>
             <% end %>

           </div>
           <div class="modal-footer">
             <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
             <button type="button" class="btn btn-primary">Save changes</button>
           </div>
         </div>
       </div>
     </div>

      </div>
    </div>
  </div>
</div>